services:
  service-api-dev:
    build:
      dockerfile: ./api/Dockerfile.dev
    container_name: service-api-dev
    ports:
      - 8443:8443
    volumes:
      - ./api:/app
      - ${PNPM_STORE_PATH}:/pnpm-store
      - /app/node_modules
    stop_grace_period: 5s
  service-db-dev:
    image: mongo:7.0.2-jammy
    container_name: service-db-dev
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-data-dev:/data/db
      - ./db/db-entry-point.sh:/usr/local/bin/db-entry-point.sh
    entrypoint: ["db-entry-point.sh"]
    command: mongod --replSet rs0
    stop_grace_period: 5s
