services:
  service-dev:
    build:
      dockerfile: dev.Dockerfile
    container_name: service-dev
    ports:
      - 8443:8443
    volumes:
      - ./:/app
      - ${PNPM_STORE_PATH}:/pnpm-store
      - /app/node_modules
    stop_grace_period: 5s
  service-db:
    image: mongo:7.0.2-jammy
    container_name: service-db
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null
    stop_grace_period: 5s
