FROM node:21.0.0-alpine3.17

WORKDIR /app

RUN corepack enable
RUN pnpm config set store-dir /pnpm-store

COPY ./api/package.json ./api/pnpm-lock.yaml ./

RUN pnpm install

COPY . .

ENV NODE_ENV=production
CMD ["pnpm", "tsx", "src/index.ts"]
