FROM node:21.0.0-alpine3.17

WORKDIR /app

RUN corepack enable
RUN pnpm config set store-dir /pnpm-store
RUN apk add --no-cache inotify-tools

COPY ./api/package.json ./api/pnpm-lock.yaml ./

RUN pnpm install

COPY . .

CMD ["sh", "./api-entry-point.dev.sh"]
